# Generated by Django 5.2.6 on 2025-11-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('password', models.CharField(max_length=128)),
                ('first_login', models.BooleanField(default=True)),
                ('temp_password', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
