# Generated by Django 5.2.6 on 2025-11-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
