# Generated by Django 5.2.6 on 2025-11-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employeeprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
