# Generated by Django 5.2.6 on 2025-11-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employeeprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
